# What is Digital Musicology? 

::: {.callout-note}
# Goal
Understanding the meanings of "digital musicology".
:::

## Introduction

Virtual all aspects of our daily lives are increasingly shaped by data and algorithms. 
This 'digital turn' has also not stopped before academia and science, 
and most fields are more and more engaging with these new methodologies.

**Digital Musicology** (DM) is a term that refers to music research that draws on digital data 
and digital methods to answer its research questions [@Pugin2015]. Stating a concise definition for the field 
is difficult, and there is no consensus to date. Moreover, a range of similar terms are 
frequently being used---for example, Computational Musicology---that have slightly different meanings. 
Faced with the fact that 
no common definition of these terms exist, Kris Shaffer attempted to describe some of 
the main aspects associated with Computational and Digital Musicology [@Schaffer2016]. 
He names the following subfields, which we will briefly discuss in turn (in an adapted order). 

## Music Encoding 

At the beginning of any digital approach to music stands the question how music 
is to be represented digitally. Music encoding in the narrower sense asks, 
how _symbolic_ musical notations such as Common Western Music Notation (CWMN) 
can be translated into a computer-readable form. 
During this course, we will get to know a few fundamental symbolic music encoding formats,
namely MIDI, ABC, and MEI. Other important formats, e.g. MusicXML or LilyPond, 
cannot be covered, unfortunately.

::: {.callout-note}
I am also teaching a course on music encoding this semester: 
[_Digitale Musikkodierung und -edition_](https://wuestudy.zv.uni-wuerzburg.de:443/qisserver/pages/startFlow.xhtml?_flowId=detailView-flow&unitId=206548&periodId=3499&navigationPosition=hisinoneLehrorganisation,examEventOverviewOwn){target="_blank"}.
:::

### Corpus Studies 

Although corpus studies are considered a modern form of music theory, 
they can look back an an astonishingly long history. Many consider the first 
corpus study to be Jeppesen's study _The Style of Palestrina and the Dissonance_,
where he counts and tabulates occurrences of dissonant vertical intervals in the 
vocal work of the Renaissance composer [@Jeppesen1927]. Further early examples 
are the dissertations of @Budge1943 and @Norman1945.

In a nutshell, corpus attempt to find regularities in large collections of 
music data [@Shanahan2022] in order to draw conclusions about the style of a particular 
composer, period, or genre, for instance. Corpus studies thus naturally make use 
of digital data and statistical or algorithmic methods for their analysis. 
Corpus studies often try to generalize music theoretical questions from the 
analysis of individual pieces to entire corpora. They often report their findings 
in statistical tables or graphical visualizations.

::: {.callout-note}
In the next summer term, I will teach a course on _Music Corpus Studies_.
:::

## Music Information Retrieval

Music information retrieval (MIR) is the largest part of DM, and research in this domain 
is directed both at academic as well as industrial contexts. MIR is closer to computer science, 
and some of its aspects can be understood as CS applied to music. The primary goal is 
not always a deeper understanding of music, but for instance improvements of recommendation 
or classification systems [@BurgoyneMIR2015]. Recently, the wave of artificial intelligence (AI) as 
inspired a renewed interest in music generation, and human-computer co-creativity. 

## Modeling 

"Modeling" in the scientific sense means to represent some aspect of reality in 
a simplified manner so that it can be easier studied and understood. If models are 
specified in such a way that machines can understand them, we speak of formal or 
computational models. Computational models can be used to perform tasks that 
are usually done by humans. For example, streaming services such as Spotify 
use computational models to categorize the songs on their platforms or 
to automatically create playlists. While models can achieve and even surpass 
human capabilities in some cases, this does not mean that computational models 
and humans use the same strategies or mechanisms to achieve certain goals. 

Therefore, computational modeling is also employed in fields such as music perception 
and cognition, where the focus does not lie on the optimal performance regarding
some task, but in the understanding of how human cognition works. 
Often, however, computational modeling and music cognition go hand in hand because 
formal models are very convenient to express complex representations or behaviors.

In this sense, Computational Musicology is part of the larger 
movement of Computational Science, an endeavour that embeds computational methods and thinking 
into domain-specific areas of research [@Wing2006]. If we have this extended view, 
we also need to include computational models of music perception and cognition, acoustics, 
and enthnological and anthropological approaches to music as well. However, this would go 
beyond the scope of this course. 


---

To sum up, what we understand by the term "Digital Musicology" depends on who you ask. 
What is common to the approaches above, however, is the development or use of digital 
methods as research tools.^[Word processors don't count, of course.]
The more computational and modeling aspects of digital music research will be covered 
in other courses. 
In this course, we focus on the following aspects of Digital Musicology, each of which 
forms an integral part of its design:

- **Data about music:** What is music metadata? How is music organized in different databases? 
  Where is the boundary between music and data?
- **Music as data:** How can music, an ephemeral expression of human culture, be captured
  or represented as digital data on a computer? What kinds of decisions do we have to make?
  Which musical aspects are retained and which are lost? Is music as data translatable?
- **Working with music data:** What kinds of questions can we ask and attempt to answer 
  when we have music data at hand? Which challenges to arise if we read instead of listening
  to music? 
- **Critical Digital Musicology**: What kinds of ethical and societal issues do we 
  touch upon when doing Digital Musicology? Which important questions do we need to consider 
  before planning or executing a research study? How does Digital Musicology relate  
  to other musicological sub-areas?

  <!-- - e.g. digital vs computational; the latter in 2nd semester -->
  <!-- - digital vs empirical vs quantiative -->
  <!-- - how does DM relate to "traditional" subdivisions of musicology? -->

::: {.callout-important}
# Organization notes

**Exercises**

Each week concludes with a number of exercises that deepen or expand 
upon the topics discussed in the seminar. Doing the exercises is essential 
for a successful completion of the course.

**Credit**

- 50% Final exam 
- 30% Exercises 
- 20% Homework
:::


[**Go to the Exercise for Week 1**](./ex/01_what_is_dm.qmd)

