# Digital Musicology today

::: {.callout-note}
# Goal
Acquiring and overview of current activities in Digital Musicology.
:::


## Institutions

::: {.callout-warning}
Obviously, the following institutional lists 
are incomplete. Luckily for the field of DM, 
it has grown so extensively that a complete overview is not possible. 
The selection below is thus not an evaluation, but rather reflects 
the familiarity of the author with those institutions and the people there.
:::

### Germany

- Paderborn/Detmold
  - [Professur für Musikwissenschaft / Digitale Edition / Digital Humanities](https://www.uni-paderborn.de/person/61139)
  - [Professur für Digitale Methoden der Musik- und Medienedition](https://www.muwi-detmold-paderborn.de/personen/professuren/prof-dr-anna-plaksin)
- Würzburg
  - [Juniorprofessur für Digitale Musikphilologie und Musiktheorie](https://www.musikwissenschaft.uni-wuerzburg.de/team/moss)
  - [Professur für Computational Humanities](https://www.caidas.uni-wuerzburg.de/ch/)
- Erlangen
  - [AudioLabs](https://www.audiolabs-erlangen.de/)
- Halle
  - [Juniorprofessur für Musikwissenschaft, Edition und Digital Humanties](https://www.musikwiss.uni-halle.de/team/dennis_ried/)

### Europe 

- London
- Linz
- Barcelona
- Lausanne 
- Amsterdam

### International

- Stanford
- MIT
- Georgia Tech
- McGill

## Organizations 

- [International Society for Music Information Retrieval (ISMIR)](https://ismir.net/)
- [International Musicological Society (IMS): Digital Musicology Study Group](https://digital.musicology.org/)
- [Fachgruppe Digitale Musikwissenschaft der Gesellschaft für Musikforschung (GfM)](https://www.musikforschung.de/digitale-musikwissenschaft/)
- [Music Encoding Initiative (MEI)](https://music-encoding.org/)

<!-- ## Current research topics -->

## Central journals and conferences

### Journals 

- [Empirical Musicology Review](https://emusicology.org/)
- [Music Perception](https://online.ucpress.edu/mp)
- [Musicae Scientiae](https://journals.sagepub.com/home/MSX)
- [Music & Science](https://journals.sagepub.com/home/mns)
- [Music Theory Online](https://www.mtosmt.org/)
- [Music Theory Spectrum](https://academic.oup.com/mts/) 

### Conferences 

- [ISMIR Conference](https://ismir.net/conferences/)
- [Digital Libraries for Musicology (DLfM)](https://dlfm.web.ox.ac.uk/)
- [International Conference on Music Perception and Cognition (ICMPC)](https://icmpc.org/icmpc_upcoming_conference.html)
- [International Conference on Computational and Cognitive Musicology (ICCCM)](https://digital.musicology.org/conferences/)
- [Computer Music Multidisciplinary Research (CMMR)](https://cmmr2025.prism.cnrs.fr/)
- [Computational Humanities Research (CHR)](https://computational-humanities-research.org/)
- [Sound and Music Computing Conference (SMC)](https://smc25.iem.at/)
- [Music Encoding Conference (MEC)](https://music-encoding.org/conference/past.html)
<!-- - DH Conference -->

## Important tools

- RISM Online
- music21 
- Verovio 

<!-- ## Study programs and summer schools -->


[**Go to the exercises for Week 2.**](ex/02_python_primer.qmd)
