project:
  type: book

book:
  title: "INTRODUCTION TO DIGITAL MUSICOLOGY"
  author: "Fabian C. Moss"
  date: "7/5/2025"
  chapters:
  - index.qmd
  - part: INTRODUCTION
    chapters:
    - 01_what_is_dm.qmd
    - 02_dm_today.qmd
    - 03_history_of_dm.qmd
  - part: DATA ABOUT MUSIC
    chapters:
    - 04_RISM.qmd
    - 05_spotify_musicbrainz.qmd
    - 06_streaming_industry.qmd
    - billboard_charts.ipynb
  - part: MUSIC AS DATA
    chapters:
    - 07_audio.qmd
    - 08_MIDI.qmd
    - 09_MEI_header.qmd
    - 10_MEI_body.qmd
  - part: WORKING WITH MUSIC DATA
    chapters:
    - 11_dma_harmony.qmd
    - 12_dma_melody.qmd
    - 03_melody_I.ipynb
    - 04_jazz_solos.ipynb
    - 05_data-driven_music_history.ipynb
  - part: CRITICAL DIGITAL MUSICOLOGY
    chapters:
    - 13_copyright.qmd
    - 14_representation.qmd
    - 15_discussion.qmd
  - part: EXERCISES
    chapters:
    - 01_exercise.qmd
  - references.qmd

bibliography: references.bib

format:
  html:
    theme: simplex # darkly
    highlight-style: github
  pdf:
    documentclass: scrbook
    papersize: a4
    geometry:
      - top=2.5cm 
      - bottom=2.5cm
      - right=2cm 
      - left=2cm
    fig-format: pdf
    pdf-engine: lualatex
    toc-depth: 2



